using System;
using FluentMigrator;
using SchoolSystem.Migrations.Constants;
using SchoolSystem.Data.Models;

namespace SchoolSystem.Migrations.Migrations
{
    [Migration(3, "students")]
    public class _0003_CreateStudentMigration : Migration
    {
        private string TableName = "students";
        public override void Down()
        {
            Delete.Table(TableName);
        }

        public override void Up()
        {
            Create.Table(TableName)
                .WithColumn("id").AsGuid().PrimaryKey()
                .WithColumn("first_name").AsString().NotNullable()
                .WithColumn("last_name").AsString().NotNullable()
                .WithColumn("address").AsString().Nullable()
                .WithColumn("class_of").AsInt16().ForeignKey("classes", "id").Nullable()
                .WithColumn("subject_01").AsString().NotNullable()
                .WithColumn("subject_02").AsString().NotNullable()
                .WithColumn("subject_03").AsString().Nullable()
                .WithColumn("is_graduated").AsString();

            Load();

        }
        private void Load()
        {
            SaveRecord("Iain", "Blaker", "", ClassesConstants.ClassSix, "Math", "Physics", "English");
            SaveRecord("Ruddie", "Vaggers", "", ClassesConstants.ClassSix, "Physics", "Math", "NA");
            SaveRecord("Myrilla", "Pryke", "9 Mitchell Avenue", ClassesConstants.ClassSix, "Math", "Physics", "English");
            SaveRecord("Brod", "Coltart", "0 Northwestern Trail", ClassesConstants.ClassSix, "Physics", "Math", "English");
            SaveRecord("Quintina", "Capeling", "", ClassesConstants.ClassSix, "Math", "Physics", "NA");
            SaveRecord("Dalt", "Berryman", "", ClassesConstants.ClassSix, "Physics", "Math", "English");
            SaveRecord("Donn", "Elstub", "2475 Garrison Center", ClassesConstants.ClassSix, "Math", "Physics", "English");
            SaveRecord("Donna", "Prue", "896 Bellgrove Road", ClassesConstants.ClassSix, "Physics", "Math", "NA");
            SaveRecord("Kaila", "Hugett", "051 6th Parkway", ClassesConstants.ClassSix, "Math", "Physics", "English");
            SaveRecord("Lem", "Bickle", "1 Merrick Pass", ClassesConstants.ClassSix, "Physics", "Math", "English");
            SaveRecord("Stacie", "Aldhouse", "6118 Magdeline Court", ClassesConstants.ClassSix, "Math", "Physics", "NA");
            SaveRecord("Edi", "Dowden", "", ClassesConstants.ClassSix, "Physics", "Math", "English");
            SaveRecord("Florencia", "Ansett", "", ClassesConstants.ClassSix, "Math", "Physics", "English");
            SaveRecord("Pauline", "Halbard", "93334 Bowman Center", ClassesConstants.ClassSix, "Physics", "Math", "NA");
            SaveRecord("Janean", "Buske", "244 American Ash Plaza", ClassesConstants.ClassSix, "Math", "Physics", "English");
            SaveRecord("Alexandr", "Madle", "33249 Kingsford Street", ClassesConstants.ClassSix, "Physics", "Math", "English");
            SaveRecord("Nikki", "Larose", "42 Kipling Junction", ClassesConstants.ClassSix, "Math", "Physics", "NA");
            SaveRecord("Vi", "Showalter", "", ClassesConstants.ClassSix, "Physics", "Math", "English");
            SaveRecord("Adham", "Elintune", "8 Norway Maple Drive", ClassesConstants.ClassSix, "Math", "Physics", "English");
            SaveRecord("Marshal", "Hustings", "37407 Northfield Park", ClassesConstants.ClassSix, "Physics", "Math", "NA");
            SaveRecord("Briant", "Dixsee", "4175 Sunfield Pass", ClassesConstants.ClassSix, "Math", "Physics", "English");
            SaveRecord("Rosemaria", "Ellis", "39905 Washington Lane", ClassesConstants.ClassSix, "Physics", "Math", "English");
            SaveRecord("Rebeka", "Sooley", "1 Dawn Trail", ClassesConstants.ClassSix, "Math", "Physics", "NA");
            SaveRecord("Angus", "Lawlee", "90402 Bobwhite Lane", ClassesConstants.ClassSix, "Physics", "Math", "English");
            SaveRecord("Brew", "Riddoch", "", ClassesConstants.ClassSix, "Math", "Physics", "English");
            SaveRecord("Sherm", "Conduit", "", ClassesConstants.ClassSix, "Physics", "Math", "NA");
            SaveRecord("Elvera", "Cyphus", "72 Artisan Court", ClassesConstants.ClassSix, "Math", "Physics", "English");
            SaveRecord("Ker", "Kilday", "", ClassesConstants.ClassSix, "Physics", "Math", "English");
            SaveRecord("Britt", "Melmar", "44729 Londonderry Junction", ClassesConstants.ClassSix, "Math", "Physics", "NA");
            SaveRecord("Jarvis", "Heaton", "506 Evergreen Alley", ClassesConstants.ClassSix, "Physics", "Math", "English");
            SaveRecord("Hobard", "Alday", "", ClassesConstants.ClassSix, "Math", "Physics", "English");
            SaveRecord("Taddeo", "Le Quesne", "", ClassesConstants.ClassSix, "Physics", "Math", "NA");
            SaveRecord("Gwendolyn", "Spinelli", "", ClassesConstants.ClassSix, "Math", "Physics", "English");
            SaveRecord("Julius", "Serck", "1 Knutson Center", ClassesConstants.ClassSix, "Physics", "Math", "English");
            SaveRecord("Danya", "Warrener", "58 Old Shore Way", ClassesConstants.ClassSix, "Math", "Physics", "NA");
            SaveRecord("Krysta", "Geffcock", "", ClassesConstants.ClassSix, "Physics", "Math", "English");
            SaveRecord("Garek", "Gookey", "654 Utah Lane", ClassesConstants.ClassSix, "Math", "Physics", "English");
            SaveRecord("Park", "Chipps", "", ClassesConstants.ClassSix, "Physics", "Math", "NA");
            SaveRecord("Adelle", "Mitten", "", ClassesConstants.ClassSix, "Math", "Physics", "English");
            SaveRecord("Wanda", "Wilbraham", "", ClassesConstants.ClassSix, "Physics", "Math", "English");
            SaveRecord("Killy", "Rubenczyk", "354 Schurz Center", ClassesConstants.ClassSix, "Math", "Physics", "NA");
            SaveRecord("Brigit", "Duckit", "", ClassesConstants.ClassSix, "Physics", "Math", "English");
            SaveRecord("Knox", "Zannutti", "93 Buell Trail", ClassesConstants.ClassSix, "Math", "Physics", "English");
            SaveRecord("Waylen", "Chaldecott", "3 Carberry Plaza", ClassesConstants.ClassSix, "Physics", "Math", "NA");
            SaveRecord("Bendicty", "Sandom", "0868 Old Shore Plaza", ClassesConstants.ClassSix, "Math", "Physics", "English");
            SaveRecord("Mal", "Stockill", "97362 Karstens Plaza", ClassesConstants.ClassSix, "Physics", "Math", "English");
            SaveRecord("Elle", "Payler", "5460 Eagan Court", ClassesConstants.ClassSix, "Math", "Physics", "NA");
            SaveRecord("Lotti", "Roseburgh", "3652 Grayhawk Lane", ClassesConstants.ClassSix, "Physics", "Math", "English");
            SaveRecord("Norrie", "Sheringham", "62 Anzinger Parkway", ClassesConstants.ClassSix, "Math", "Physics", "English");
            SaveRecord("Ring", "Diddams", "014 Crest Line Plaza", ClassesConstants.ClassSix, "Physics", "Math", "NA");
            SaveRecord("Aristotle", "Hartlebury", "", ClassesConstants.ClassSix, "Math", "Physics", "English");
            SaveRecord("Theodore", "Sibbit", "5532 Summer Ridge Terrace", ClassesConstants.ClassSix, "Physics", "Math", "English");
            SaveRecord("Madlin", "O'Kelly", "9 Mayfield Junction", ClassesConstants.ClassSix, "Math", "Physics", "NA");
            SaveRecord("Chris", "Licciardello", "", ClassesConstants.ClassSix, "Physics", "Math", "English");
            SaveRecord("Klaus", "Crewe", "8 Westridge Road", ClassesConstants.ClassSix, "Math", "Physics", "English");
            SaveRecord("Granger", "Angove", "5392 Del Sol Hill", ClassesConstants.ClassSix, "Physics", "Math", "NA");
            SaveRecord("Johnnie", "Winters", "780 Hansons Street", ClassesConstants.ClassSix, "Math", "Physics", "English");
            SaveRecord("Mauricio", "Bowell", "63 Mayer Point", ClassesConstants.ClassSix, "Physics", "Math", "English");
            SaveRecord("Julita", "Littleproud", "42 Sugar Circle", ClassesConstants.ClassSix, "Math", "Physics", "NA");
            SaveRecord("Arne", "Elijahu", "9357 Hoard Parkway", ClassesConstants.ClassSix, "Physics", "Math", "English");
            SaveRecord("Joey", "Lowthian", "386 Bultman Park", ClassesConstants.ClassSix, "Math", "Physics", "English");
            SaveRecord("Teressa", "Gooly", "", ClassesConstants.ClassSix, "Physics", "Math", "NA");
            SaveRecord("Reynold", "Burbury", "61 Brown Drive", ClassesConstants.ClassSix, "Math", "Physics", "English");
            SaveRecord("Abdel", "Thorsen", "", ClassesConstants.ClassSix, "Physics", "Math", "English");
            SaveRecord("Brigida", "Quig", "", ClassesConstants.ClassSix, "Math", "Physics", "NA");
            SaveRecord("Shantee", "Wallsworth", "348 Alpine Plaza", ClassesConstants.ClassSix, "Physics", "Math", "English");
            SaveRecord("Gladys", "Hover", "418 Comanche Place", ClassesConstants.ClassSix, "Math", "Physics", "English");
            SaveRecord("Jocelyn", "Jindracek", "", ClassesConstants.ClassSix, "Physics", "Math", "NA");
            SaveRecord("Alvina", "Sadat", "6912 Melvin Way", ClassesConstants.ClassSix, "Math", "Physics", "English");
            SaveRecord("Bary", "McDool", "", ClassesConstants.ClassSix, "Physics", "Math", "English");
            SaveRecord("Lavena", "Melchior", "", ClassesConstants.ClassSix, "Math", "Physics", "NA");
            SaveRecord("Brice", "Worrell", "8013 Sherman Trail", ClassesConstants.ClassSix, "Physics", "Math", "English");
            SaveRecord("Filia", "Kelland", "", ClassesConstants.ClassSix, "Math", "Physics", "English");
            SaveRecord("Justine", "Denyukhin", "", ClassesConstants.ClassSix, "Physics", "Math", "NA");
            SaveRecord("Jeannine", "Bullough", "", ClassesConstants.ClassSix, "Math", "Physics", "English");
            SaveRecord("Booth", "Carlo", "00 Granby Park", ClassesConstants.ClassSix, "Physics", "Math", "English");
            SaveRecord("Dita", "Reck", "", ClassesConstants.ClassSix, "Math", "Physics", "NA");
            SaveRecord("Bobina", "Pengelley", "797 Del Mar Street", ClassesConstants.ClassSix, "Physics", "Math", "English");
            SaveRecord("Carolynn", "Arnold", "729 Annamark Point", ClassesConstants.ClassSix, "Math", "Physics", "English");
            SaveRecord("Belle", "Cakebread", "4084 Vidon Park", ClassesConstants.ClassSix, "Physics", "Math", "NA");
            SaveRecord("Sheffie", "Luck", "", ClassesConstants.ClassSix, "Math", "Physics", "English");
            SaveRecord("Griffie", "Gatecliff", "01367 Independence Road", ClassesConstants.ClassSix, "Physics", "Math", "English");
            SaveRecord("Tillie", "Duberry", "", ClassesConstants.ClassSix, "Math", "Physics", "NA");
            SaveRecord("Pansie", "Guye", "42 Reindahl Trail", ClassesConstants.ClassSix, "Physics", "Math", "English");
            SaveRecord("Binnie", "Luesley", "", ClassesConstants.ClassSeven, "Math", "Physics", "English");
            SaveRecord("Merl", "Rizzardini", "96946 Sycamore Drive", ClassesConstants.ClassSeven, "Physics", "Math", "NA");
            SaveRecord("Blayne", "Showalter", "82541 Lakewood Gardens Drive", ClassesConstants.ClassSeven, "Math", "Physics", "English");
            SaveRecord("Sharl", "Potbury", "9 Riverside Center", ClassesConstants.ClassSeven, "Physics", "Math", "English");
            SaveRecord("Zacharias", "Elman", "25685 West Pass", ClassesConstants.ClassSeven, "Math", "Physics", "NA");
            SaveRecord("Boot", "Pedlow", "8 Kinsman Pass", ClassesConstants.ClassSeven, "Physics", "Math", "English");
            SaveRecord("Averell", "Fairey", "7291 Waywood Hill", ClassesConstants.ClassSeven, "Math", "Physics", "English");
            SaveRecord("Heddie", "Aharoni", "", ClassesConstants.ClassSeven, "Physics", "Math", "NA");
            SaveRecord("Deck", "Pepin", "", ClassesConstants.ClassSeven, "Math", "Physics", "English");
            SaveRecord("Richart", "Fischer", "8 Mallory Trail", ClassesConstants.ClassSeven, "Physics", "Math", "English");
            SaveRecord("Noak", "Georgins", "30 Iowa Center", ClassesConstants.ClassSeven, "Math", "Physics", "NA");
            SaveRecord("Pall", "Rive", "8 Sutherland Point", ClassesConstants.ClassSeven, "Physics", "Math", "English");
            SaveRecord("Bekki", "Abramovitz", "52954 Cascade Park", ClassesConstants.ClassSeven, "Math", "Physics", "English");
            SaveRecord("Dix", "Nickels", "44 Killdeer Terrace", ClassesConstants.ClassSeven, "Physics", "Math", "NA");
            SaveRecord("Julius", "Vautier", "28 Sugar Hill", ClassesConstants.ClassSeven, "Math", "Physics", "English");
            SaveRecord("Ninette", "Laidler", "93924 Messerschmidt Parkway", ClassesConstants.ClassSeven, "Physics", "Math", "English");
            SaveRecord("Nolie", "Comelini", "5 Dakota Avenue", ClassesConstants.ClassSeven, "Math", "Physics", "NA");
            SaveRecord("Breanne", "Talbot", "8800 American Ash Park", ClassesConstants.ClassSeven, "Physics", "Math", "English");
            SaveRecord("Linnea", "Tadd", "", ClassesConstants.ClassSeven, "Math", "Physics", "English");
            SaveRecord("Carroll", "Macer", "", ClassesConstants.ClassSeven, "Physics", "Math", "NA");
            SaveRecord("Hatti", "Shellsheere", "", ClassesConstants.ClassSeven, "Math", "Physics", "English");
            SaveRecord("Korry", "Weiser", "", ClassesConstants.ClassSeven, "Physics", "Math", "English");
            SaveRecord("Rivkah", "Ahrend", "", ClassesConstants.ClassSeven, "Math", "Physics", "NA");
            SaveRecord("Marga", "Fearney", "4 Northfield Trail", ClassesConstants.ClassSeven, "Physics", "Math", "English");
            SaveRecord("Ivan", "McKilroe", "", ClassesConstants.ClassSeven, "Math", "Physics", "English");
            SaveRecord("Donnie", "Aldersey", "7 Homewood Point", ClassesConstants.ClassSeven, "Physics", "Math", "NA");
            SaveRecord("Lyndsey", "Tabbernor", "", ClassesConstants.ClassSeven, "Math", "Physics", "English");
            SaveRecord("Alfons", "Stormonth", "", ClassesConstants.ClassSeven, "Physics", "Math", "English");
            SaveRecord("Engelbert", "Reinhard", "", ClassesConstants.ClassSeven, "Math", "Physics", "NA");
            SaveRecord("Wenda", "Rawlison", "1 Farwell Hill", ClassesConstants.ClassSeven, "Physics", "Math", "English");
            SaveRecord("Emlen", "Haimes", "66 Fremont Lane", ClassesConstants.ClassSeven, "Math", "Physics", "English");
            SaveRecord("Tobias", "Frend", "", ClassesConstants.ClassSeven, "Physics", "Math", "NA");
            SaveRecord("Cam", "Hardson", "7 Glendale Hill", ClassesConstants.ClassSeven, "Math", "Physics", "English");
            SaveRecord("Lock", "Croft", "77 Fieldstone Circle", ClassesConstants.ClassSeven, "Physics", "Math", "English");
            SaveRecord("Leann", "Zuanazzi", "", ClassesConstants.ClassSeven, "Math", "Physics", "NA");
            SaveRecord("Eimile", "Tuffield", "", ClassesConstants.ClassSeven, "Physics", "Math", "English");
            SaveRecord("Lannie", "Cockshutt", "", ClassesConstants.ClassSeven, "Math", "Physics", "English");
            SaveRecord("Read", "Fairfull", "791 Nova Terrace", ClassesConstants.ClassSeven, "Physics", "Math", "NA");
            SaveRecord("Davey", "Fedorchenko", "", ClassesConstants.ClassSeven, "Math", "Physics", "English");
            SaveRecord("Osborn", "Vigne", "11 Raven Alley", ClassesConstants.ClassSeven, "Physics", "Math", "English");
            SaveRecord("Maighdiln", "Ferrick", "2360 Ridge Oak Drive", ClassesConstants.ClassSeven, "Math", "Physics", "NA");
            SaveRecord("Dore", "Kulver", "894 Blaine Alley", ClassesConstants.ClassSeven, "Physics", "Math", "English");
            SaveRecord("Demetrius", "Kurtis", "", ClassesConstants.ClassSeven, "Math", "Physics", "English");
            SaveRecord("Chad", "Crew", "", ClassesConstants.ClassSeven, "Physics", "Math", "NA");
            SaveRecord("Gilberta", "Beagrie", "0319 Ohio Street", ClassesConstants.ClassSeven, "Math", "Physics", "English");
            SaveRecord("Loy", "McFarland", "", ClassesConstants.ClassSeven, "Physics", "Math", "English");
            SaveRecord("Jillie", "Seif", "", ClassesConstants.ClassSeven, "Math", "Physics", "NA");
            SaveRecord("Abigael", "Gelsthorpe", "", ClassesConstants.ClassSeven, "Physics", "Math", "English");
            SaveRecord("Vivien", "Shaw", "", ClassesConstants.ClassSeven, "Math", "Physics", "English");
            SaveRecord("Kizzee", "Tennet", "", ClassesConstants.ClassSeven, "Physics", "Math", "NA");
            SaveRecord("Granger", "Burgiss", "", ClassesConstants.ClassSeven, "Math", "Physics", "English");
            SaveRecord("Carilyn", "Higgonet", "8628 Packers Park", ClassesConstants.ClassSeven, "Physics", "Math", "English");
            SaveRecord("Daniel", "Stanmer", "40711 Scott Parkway", ClassesConstants.ClassSeven, "Math", "Physics", "NA");
            SaveRecord("Hughie", "Wolpert", "4 Brown Point", ClassesConstants.ClassSeven, "Physics", "Math", "English");
            SaveRecord("Dennet", "Decruse", "1 Redwing Crossing", ClassesConstants.ClassSeven, "Math", "Physics", "English");
            SaveRecord("Sutton", "Tunuy", "87 Bobwhite Court", ClassesConstants.ClassSeven, "Physics", "Math", "NA");
            SaveRecord("Page", "Bosche", "0 Service Parkway", ClassesConstants.ClassSeven, "Math", "Physics", "English");
            SaveRecord("Anna-maria", "Meindl", "", ClassesConstants.ClassSeven, "Physics", "Math", "English");
            SaveRecord("Cirstoforo", "Imlach", "", ClassesConstants.ClassSeven, "Math", "Physics", "NA");
            SaveRecord("Cammy", "Mingardi", "4931 Caliangt Hill", ClassesConstants.ClassSeven, "Physics", "Math", "English");
            SaveRecord("Deloria", "Grubey", "", ClassesConstants.ClassSeven, "Math", "Physics", "English");
            SaveRecord("Kala", "Hemmingway", "26 Kinsman Trail", ClassesConstants.ClassSeven, "Physics", "Math", "NA");
            SaveRecord("Yancey", "Pepys", "9 Heath Hill", ClassesConstants.ClassSeven, "Math", "Physics", "English");
            SaveRecord("Henri", "Cultcheth", "", ClassesConstants.ClassSeven, "Physics", "Math", "English");
            SaveRecord("Tiphanie", "Pasticznyk", "", ClassesConstants.ClassSeven, "Math", "Physics", "NA");
            SaveRecord("Susana", "Binley", "32121 Paget Road", ClassesConstants.ClassSeven, "Physics", "Math", "English");
            SaveRecord("Teddi", "Dawid", "46875 Farmco Point", ClassesConstants.ClassSeven, "Math", "Physics", "English");
            SaveRecord("Libby", "Chapple", "", ClassesConstants.ClassSeven, "Physics", "Math", "NA");
            SaveRecord("Ileane", "Scrooby", "", ClassesConstants.ClassSeven, "Math", "Physics", "English");
            SaveRecord("Lyn", "Esposi", "8 Nancy Alley", ClassesConstants.ClassSeven, "Physics", "Math", "English");
            SaveRecord("Mala", "Morales", "75029 Sullivan Point", ClassesConstants.ClassSeven, "Math", "Physics", "NA");
            SaveRecord("Jeana", "Tocque", "03708 Northport Junction", ClassesConstants.ClassSeven, "Physics", "Math", "English");
            SaveRecord("Judye", "Wohler", "82 Petterle Avenue", ClassesConstants.ClassSeven, "Math", "Physics", "English");
            SaveRecord("Lauryn", "Swinfen", "", ClassesConstants.ClassSeven, "Physics", "Math", "NA");
            SaveRecord("Desiri", "Asson", "", ClassesConstants.ClassSeven, "Math", "Physics", "English");
            SaveRecord("Tabbi", "Tremble", "2 Corry Center", ClassesConstants.ClassSeven, "Physics", "Math", "English");
            SaveRecord("Erroll", "Vasyunin", "", ClassesConstants.ClassSeven, "Math", "Physics", "NA");
            SaveRecord("Romy", "Hause", "4 Chinook Point", ClassesConstants.ClassSeven, "Physics", "Math", "English");
            SaveRecord("Alard", "Tirrell", "", ClassesConstants.ClassSeven, "Math", "Physics", "English");
            SaveRecord("Doralin", "Sleath", "", ClassesConstants.ClassSeven, "Physics", "Math", "NA");
            SaveRecord("Evangelin", "Bolwell", "126 Dayton Alley", ClassesConstants.ClassSeven, "Math", "Physics", "English");
            SaveRecord("Karel", "Whittock", "", ClassesConstants.ClassSeven, "Physics", "Math", "English");
            SaveRecord("Biron", "Seiler", "29 Cordelia Point", ClassesConstants.ClassSeven, "Math", "Physics", "NA");
            SaveRecord("Mozes", "Charlwood", "24004 Ridge Oak Hill", ClassesConstants.ClassSeven, "Physics", "Math", "English");
            SaveRecord("Susan", "Clarae", "", ClassesConstants.ClassEight, "Math", "Physics", "English");
            SaveRecord("Francois", "Antonazzi", "", ClassesConstants.ClassEight, "Physics", "Math", "NA");
            SaveRecord("Jinny", "Freire", "890 Kinsman Trail", ClassesConstants.ClassEight, "Math", "Physics", "English");
            SaveRecord("Durand", "Nitto", "", ClassesConstants.ClassEight, "Physics", "Math", "English");
            SaveRecord("Stefa", "Haddy", "6 Fairfield Road", ClassesConstants.ClassEight, "Math", "Physics", "NA");
            SaveRecord("Laurence", "Braithwait", "", ClassesConstants.ClassEight, "Physics", "Math", "English");
            SaveRecord("Lowe", "Glavis", "", ClassesConstants.ClassEight, "Math", "Physics", "English");
            SaveRecord("Vernen", "Marron", "", ClassesConstants.ClassEight, "Physics", "Math", "NA");
            SaveRecord("Prudence", "Ruselin", "6 Oneill Alley", ClassesConstants.ClassEight, "Math", "Physics", "English");
            SaveRecord("Fidelio", "Hanson", "", ClassesConstants.ClassEight, "Physics", "Math", "English");
            SaveRecord("Othilie", "Keats", "", ClassesConstants.ClassEight, "Math", "Physics", "NA");
            SaveRecord("Audry", "Guiett", "30 Meadow Vale Way", ClassesConstants.ClassEight, "Physics", "Math", "English");
            SaveRecord("Anabel", "Kores", "459 Randy Trail", ClassesConstants.ClassEight, "Math", "Physics", "English");
            SaveRecord("Teddy", "Scramage", "", ClassesConstants.ClassEight, "Physics", "Math", "NA");
            SaveRecord("Keslie", "Visick", "", ClassesConstants.ClassEight, "Math", "Physics", "English");
            SaveRecord("Petrina", "McKyrrelly", "796 Garrison Trail", ClassesConstants.ClassEight, "Physics", "Math", "English");
            SaveRecord("Antons", "Gullifant", "35 Welch Way", ClassesConstants.ClassEight, "Math", "Physics", "NA");
            SaveRecord("Faun", "Phelp", "108 Florence Circle", ClassesConstants.ClassEight, "Physics", "Math", "English");
            SaveRecord("Caralie", "Tuddall", "15958 Calypso Crossing", ClassesConstants.ClassEight, "Math", "Physics", "English");
            SaveRecord("Berna", "Stannislawski", "", ClassesConstants.ClassEight, "Physics", "Math", "NA");
            SaveRecord("Worthy", "Lindstedt", "", ClassesConstants.ClassEight, "Math", "Physics", "English");
            SaveRecord("Sophey", "Niccolls", "470 Morning Road", ClassesConstants.ClassEight, "Physics", "Math", "English");
            SaveRecord("Harley", "Joscelin", "", ClassesConstants.ClassEight, "Math", "Physics", "NA");
            SaveRecord("Rosabelle", "Libbie", "98 Ludington Junction", ClassesConstants.ClassEight, "Physics", "Math", "English");
            SaveRecord("Saba", "Gibberd", "3703 Helena Plaza", ClassesConstants.ClassEight, "Math", "Physics", "English");
            SaveRecord("Del", "Duffrie", "875 New Castle Point", ClassesConstants.ClassEight, "Physics", "Math", "NA");
            SaveRecord("Kain", "Rocco", "", ClassesConstants.ClassEight, "Math", "Physics", "English");
            SaveRecord("Valentino", "MacCaig", "05 Canary Street", ClassesConstants.ClassEight, "Physics", "Math", "English");
            SaveRecord("Quinn", "De la Yglesia", "", ClassesConstants.ClassEight, "Math", "Physics", "NA");
            SaveRecord("Jermaine", "Darte", "", ClassesConstants.ClassEight, "Physics", "Math", "English");
            SaveRecord("Sholom", "Weathers", "2990 Fuller Road", ClassesConstants.ClassEight, "Math", "Physics", "English");
            SaveRecord("Leroy", "Mcsarry", "76072 Farmco Street", ClassesConstants.ClassEight, "Physics", "Math", "NA");
            SaveRecord("Lesley", "Westberg", "", ClassesConstants.ClassEight, "Math", "Physics", "English");
            SaveRecord("Josy", "Tutsell", "", ClassesConstants.ClassEight, "Physics", "Math", "English");
            SaveRecord("Ernesto", "Bransdon", "70453 Prairie Rose Plaza", ClassesConstants.ClassEight, "Math", "Physics", "NA");
            SaveRecord("Ernesta", "Bolver", "02952 Orin Plaza", ClassesConstants.ClassEight, "Physics", "Math", "English");
            SaveRecord("Toby", "Shavel", "7236 Pepper Wood Park", ClassesConstants.ClassEight, "Math", "Physics", "English");
            SaveRecord("Tomasina", "Scawn", "8606 Warner Circle", ClassesConstants.ClassEight, "Physics", "Math", "NA");
            SaveRecord("Ogdan", "Keneleyside", "", ClassesConstants.ClassEight, "Math", "Physics", "English");
            SaveRecord("Emera", "Blencoe", "95 Colorado Crossing", ClassesConstants.ClassEight, "Physics", "Math", "English");
            SaveRecord("Ansel", "Tybalt", "961 Mcbride Way", ClassesConstants.ClassEight, "Math", "Physics", "NA");
            SaveRecord("Sauncho", "Scholefield", "5971 Melvin Parkway", ClassesConstants.ClassEight, "Physics", "Math", "English");
            SaveRecord("Currey", "Angell", "15 Maywood Circle", ClassesConstants.ClassEight, "Math", "Physics", "English");
            SaveRecord("Noellyn", "Klementz", "1 Porter Road", ClassesConstants.ClassEight, "Physics", "Math", "NA");
            SaveRecord("Kathy", "MacMenamin", "74432 Sundown Place", ClassesConstants.ClassEight, "Math", "Physics", "English");
            SaveRecord("Vannie", "Syson", "7098 Briar Crest Way", ClassesConstants.ClassEight, "Physics", "Math", "English");
            SaveRecord("Wadsworth", "Dellenbroker", "", ClassesConstants.ClassEight, "Math", "Physics", "NA");
            SaveRecord("Modestine", "Croysdale", "4185 Nelson Parkway", ClassesConstants.ClassEight, "Physics", "Math", "English");
            SaveRecord("Ashia", "Mattheis", "4451 Melby Way", ClassesConstants.ClassEight, "Math", "Physics", "English");
            SaveRecord("Kimberli", "Oiseau", "", ClassesConstants.ClassEight, "Physics", "Math", "NA");
            SaveRecord("Louise", "Schukert", "57507 Montana Street", ClassesConstants.ClassEight, "Math", "Physics", "English");
            SaveRecord("Jarib", "Tartt", "57764 Susan Pass", ClassesConstants.ClassEight, "Physics", "Math", "English");
            SaveRecord("Hamish", "Kail", "5 Ridge Oak Trail", ClassesConstants.ClassEight, "Math", "Physics", "NA");
            SaveRecord("Kin", "Beacham", "9694 Mockingbird Place", ClassesConstants.ClassEight, "Physics", "Math", "English");
            SaveRecord("Purcell", "Sherrott", "93684 Cottonwood Alley", ClassesConstants.ClassEight, "Math", "Physics", "English");
            SaveRecord("Megan", "Quene", "", ClassesConstants.ClassEight, "Physics", "Math", "NA");
            SaveRecord("Maxy", "Clem", "62 Maple Wood Lane", ClassesConstants.ClassEight, "Math", "Physics", "English");
            SaveRecord("Dukie", "Girvin", "22 Valley Edge Circle", ClassesConstants.ClassEight, "Physics", "Math", "English");
            SaveRecord("Zonnya", "Elleton", "", ClassesConstants.ClassEight, "Math", "Physics", "NA");
            SaveRecord("Ronnica", "Woloschin", "", ClassesConstants.ClassEight, "Physics", "Math", "English");
            SaveRecord("Bert", "Gellier", "4 Arizona Avenue", ClassesConstants.ClassEight, "Math", "Physics", "English");
            SaveRecord("Brenden", "Priditt", "", ClassesConstants.ClassEight, "Physics", "Math", "NA");
            SaveRecord("Glennis", "McKelvey", "3865 Southridge Way", ClassesConstants.ClassEight, "Math", "Physics", "English");
            SaveRecord("Hanni", "Shute", "", ClassesConstants.ClassEight, "Physics", "Math", "English");
            SaveRecord("Tarrance", "Piwell", "", ClassesConstants.ClassEight, "Math", "Physics", "NA");
            SaveRecord("Isabelita", "Fenge", "345 Bunting Pass", ClassesConstants.ClassEight, "Physics", "Math", "English");
            SaveRecord("Kessia", "Gertray", "432 Union Trail", ClassesConstants.ClassEight, "Math", "Physics", "English");
            SaveRecord("Sylvester", "Clubley", "", ClassesConstants.ClassEight, "Physics", "Math", "NA");
            SaveRecord("Jada", "Aloshkin", "19689 Algoma Parkway", ClassesConstants.ClassEight, "Math", "Physics", "English");
            SaveRecord("Marcille", "Kneeland", "3 Crescent Oaks Park", ClassesConstants.ClassEight, "Physics", "Math", "English");
            SaveRecord("Laurie", "Flatte", "59 Longview Drive", ClassesConstants.ClassEight, "Math", "Physics", "NA");
            SaveRecord("Devondra", "Bould", "", ClassesConstants.ClassEight, "Physics", "Math", "English");
            SaveRecord("Gabbey", "Williscroft", "24586 Forest Place", ClassesConstants.ClassEight, "Math", "Physics", "English");
            SaveRecord("Taite", "Classen", "7 Myrtle Drive", ClassesConstants.ClassEight, "Physics", "Math", "NA");
            SaveRecord("Boy", "Bannon", "", ClassesConstants.ClassEight, "Math", "Physics", "English");
            SaveRecord("Corine", "Tison", "73574 School Court", ClassesConstants.ClassEight, "Physics", "Math", "English");
            SaveRecord("Marchelle", "Cleere", "", ClassesConstants.ClassEight, "Math", "Physics", "NA");
            SaveRecord("Hobey", "Shellsheere", "132 Center Place", ClassesConstants.ClassEight, "Physics", "Math", "English");
            SaveRecord("Roxy", "Storey", "", ClassesConstants.ClassEight, "Math", "Physics", "English");
            SaveRecord("Allen", "Scotland", "20 Gateway Plaza", ClassesConstants.ClassEight, "Physics", "Math", "NA");
            SaveRecord("Letisha", "Starten", "501 Shelley Avenue", ClassesConstants.ClassEight, "Math", "Physics", "English");
            SaveRecord("Jerrie", "Coultar", "8076 Village Circle", ClassesConstants.ClassEight, "Physics", "Math", "English");
            SaveRecord("Beltran", "Berthe", "", ClassesConstants.ClassEight, "Math", "Physics", "NA");
            SaveRecord("Petronella", "Slinger", "", ClassesConstants.ClassEight, "Physics", "Math", "English");
            SaveRecord("Shawnee", "Heibl", "", ClassesConstants.ClassNine, "Math", "Physics", "English");
            SaveRecord("Wes", "Haddick", "5599 7th Center", ClassesConstants.ClassNine, "Physics", "Math", "NA");
            SaveRecord("Blake", "Matteris", "0280 Farwell Pass", ClassesConstants.ClassNine, "Math", "Physics", "English");
            SaveRecord("Lexy", "Letts", "893 Buell Lane", ClassesConstants.ClassNine, "Physics", "Math", "English");
            SaveRecord("Gail", "Birth", "3 Havey Road", ClassesConstants.ClassNine, "Math", "Physics", "NA");
            SaveRecord("Anna", "Lardeux", "", ClassesConstants.ClassNine, "Physics", "Math", "English");
            SaveRecord("Kristina", "Lambole", "343 Warner Point", ClassesConstants.ClassNine, "Math", "Physics", "English");
            SaveRecord("Andi", "Mahood", "", ClassesConstants.ClassNine, "Physics", "Math", "NA");
            SaveRecord("Dollie", "Colthard", "6116 Carioca Pass", ClassesConstants.ClassNine, "Math", "Physics", "English");
            SaveRecord("Chauncey", "Midgely", "", ClassesConstants.ClassNine, "Physics", "Math", "English");
            SaveRecord("Dolores", "Melvin", "", ClassesConstants.ClassNine, "Math", "Physics", "NA");
            SaveRecord("Noami", "Ixer", "", ClassesConstants.ClassNine, "Physics", "Math", "English");
            SaveRecord("Giordano", "Forcer", "8813 Sauthoff Road", ClassesConstants.ClassNine, "Math", "Physics", "English");
            SaveRecord("Blake", "Menico", "", ClassesConstants.ClassNine, "Physics", "Math", "NA");
            SaveRecord("Jolynn", "Lines", "", ClassesConstants.ClassNine, "Math", "Physics", "English");
            SaveRecord("Cly", "Headan", "55938 New Castle Avenue", ClassesConstants.ClassNine, "Physics", "Math", "English");
            SaveRecord("Georgy", "Creak", "9002 North Parkway", ClassesConstants.ClassNine, "Math", "Physics", "NA");
            SaveRecord("Osbourne", "Canet", "", ClassesConstants.ClassNine, "Physics", "Math", "English");
            SaveRecord("Laurence", "Gainsborough", "334 Sullivan Avenue", ClassesConstants.ClassNine, "Math", "Physics", "English");
            SaveRecord("Germaine", "McKeon", "4 Iowa Hill", ClassesConstants.ClassNine, "Physics", "Math", "NA");
            SaveRecord("Donetta", "Parry", "", ClassesConstants.ClassNine, "Math", "Physics", "English");
            SaveRecord("Rodi", "Tench", "", ClassesConstants.ClassNine, "Physics", "Math", "English");
            SaveRecord("Libbey", "Bailes", "1700 Morrow Way", ClassesConstants.ClassNine, "Math", "Physics", "NA");
            SaveRecord("Markus", "Jopke", "", ClassesConstants.ClassNine, "Physics", "Math", "English");
            SaveRecord("Ellen", "Hatherley", "49 Mayer Way", ClassesConstants.ClassNine, "Math", "Physics", "English");
            SaveRecord("Giacomo", "Milne", "0 Rockefeller Plaza", ClassesConstants.ClassNine, "Physics", "Math", "NA");
            SaveRecord("Brier", "Elix", "0300 Sutherland Court", ClassesConstants.ClassNine, "Math", "Physics", "English");
            SaveRecord("Jasper", "Peasegod", "3715 Stephen Trail", ClassesConstants.ClassNine, "Physics", "Math", "English");
            SaveRecord("Stacee", "Lazar", "39254 Burning Wood Court", ClassesConstants.ClassNine, "Math", "Physics", "NA");
            SaveRecord("Gardener", "Sharvell", "", ClassesConstants.ClassNine, "Physics", "Math", "English");
            SaveRecord("Melva", "Shawl", "8 Eastlawn Hill", ClassesConstants.ClassNine, "Math", "Physics", "English");
            SaveRecord("Joly", "Fetherston", "62523 Fulton Lane", ClassesConstants.ClassNine, "Physics", "Math", "NA");
            SaveRecord("Nev", "Searle", "0 Dakota Road", ClassesConstants.ClassNine, "Math", "Physics", "English");
            SaveRecord("Amby", "Jurewicz", "83801 Granby Court", ClassesConstants.ClassNine, "Physics", "Math", "English");
            SaveRecord("Wilone", "Giovanizio", "98851 Waubesa Pass", ClassesConstants.ClassNine, "Math", "Physics", "NA");
            SaveRecord("Vyky", "Doneld", "6689 Thackeray Avenue", ClassesConstants.ClassNine, "Physics", "Math", "English");
            SaveRecord("Bax", "Medway", "", ClassesConstants.ClassNine, "Math", "Physics", "English");
            SaveRecord("Bil", "Hollow", "65 Morrow Court", ClassesConstants.ClassNine, "Physics", "Math", "NA");
            SaveRecord("Peggie", "Akeherst", "", ClassesConstants.ClassNine, "Math", "Physics", "English");
            SaveRecord("Evangelia", "Schnitter", "777 Hallows Circle", ClassesConstants.ClassNine, "Physics", "Math", "English");
            SaveRecord("Kameko", "Bugg", "", ClassesConstants.ClassNine, "Math", "Physics", "NA");
            SaveRecord("Reggie", "Tapsell", "", ClassesConstants.ClassNine, "Physics", "Math", "English");
            SaveRecord("Ahmed", "Barham", "586 Debs Terrace", ClassesConstants.ClassNine, "Math", "Physics", "English");
            SaveRecord("Roz", "Stirgess", "", ClassesConstants.ClassNine, "Physics", "Math", "NA");
            SaveRecord("Ivor", "Featherstonhaugh", "03 Nova Place", ClassesConstants.ClassNine, "Math", "Physics", "English");
            SaveRecord("Lacy", "Basant", "", ClassesConstants.ClassNine, "Physics", "Math", "English");
            SaveRecord("Alexandro", "Bancroft", "", ClassesConstants.ClassNine, "Math", "Physics", "NA");
            SaveRecord("Taylor", "Doohey", "18 Namekagon Drive", ClassesConstants.ClassNine, "Physics", "Math", "English");
            SaveRecord("Town", "Cowerd", "10813 Schiller Center", ClassesConstants.ClassNine, "Math", "Physics", "English");
            SaveRecord("Lona", "Burns", "498 Sloan Circle", ClassesConstants.ClassNine, "Physics", "Math", "NA");
            SaveRecord("Sarge", "Bremond", "7 Lighthouse Bay Terrace", ClassesConstants.ClassNine, "Math", "Physics", "English");
            SaveRecord("Rog", "Allnatt", "6 Killdeer Way", ClassesConstants.ClassNine, "Physics", "Math", "English");
            SaveRecord("Bennett", "Rahill", "", ClassesConstants.ClassNine, "Math", "Physics", "NA");
            SaveRecord("Arden", "McSwan", "", ClassesConstants.ClassNine, "Physics", "Math", "English");
            SaveRecord("Grant", "Jefferies", "76 Merry Street", ClassesConstants.ClassNine, "Math", "Physics", "English");
            SaveRecord("Claybourne", "Pyke", "", ClassesConstants.ClassNine, "Physics", "Math", "NA");
            SaveRecord("Cathyleen", "Thieme", "", ClassesConstants.ClassNine, "Math", "Physics", "English");
            SaveRecord("Ketti", "Phoenix", "3 Lighthouse Bay Junction", ClassesConstants.ClassNine, "Physics", "Math", "English");
            SaveRecord("Micky", "Barratt", "78 Bunting Road", ClassesConstants.ClassNine, "Math", "Physics", "NA");
            SaveRecord("Brad", "Chislett", "", ClassesConstants.ClassNine, "Physics", "Math", "English");
            SaveRecord("Renault", "Gilardoni", "", ClassesConstants.ClassNine, "Math", "Physics", "English");
            SaveRecord("Carissa", "Immer", "", ClassesConstants.ClassNine, "Physics", "Math", "NA");
            SaveRecord("Jacinthe", "Seldner", "", ClassesConstants.ClassNine, "Math", "Physics", "English");
            SaveRecord("Diandra", "Camacho", "", ClassesConstants.ClassNine, "Physics", "Math", "English");
            SaveRecord("Kelley", "Edghinn", "922 Northport Terrace", ClassesConstants.ClassNine, "Math", "Physics", "NA");
            SaveRecord("Cybill", "Phaup", "5507 Vera Alley", ClassesConstants.ClassNine, "Physics", "Math", "English");
            SaveRecord("Morse", "Plante", "", ClassesConstants.ClassNine, "Math", "Physics", "English");
            SaveRecord("Latia", "Tommei", "", ClassesConstants.ClassNine, "Physics", "Math", "NA");
            SaveRecord("Dulcinea", "Bergstram", "", ClassesConstants.ClassNine, "Math", "Physics", "English");
            SaveRecord("Colby", "Cowx", "", ClassesConstants.ClassNine, "Physics", "Math", "English");
            SaveRecord("Cooper", "Martinovic", "276 Packers Point", ClassesConstants.ClassNine, "Math", "Physics", "NA");
            SaveRecord("Padraig", "Baudon", "", ClassesConstants.ClassNine, "Physics", "Math", "English");
            SaveRecord("Sherm", "Swancock", "564 Ridgeview Pass", ClassesConstants.ClassNine, "Math", "Physics", "English");
            SaveRecord("Farr", "Grindlay", "72 Pennsylvania Drive", ClassesConstants.ClassNine, "Physics", "Math", "NA");
            SaveRecord("Audrye", "Armatys", "65 Golf Course Terrace", ClassesConstants.ClassNine, "Math", "Physics", "English");
            SaveRecord("Ingmar", "Posnette", "5724 Stoughton Terrace", ClassesConstants.ClassNine, "Physics", "Math", "English");
            SaveRecord("Octavius", "Guidi", "", ClassesConstants.ClassNine, "Math", "Physics", "NA");
            SaveRecord("Belva", "Spur", "", ClassesConstants.ClassNine, "Physics", "Math", "English");
            SaveRecord("Timmie", "Mothersdale", "61135 Tomscot Road", ClassesConstants.ClassNine, "Math", "Physics", "English");
            SaveRecord("Beckie", "Thewlis", "39144 Walton Trail", ClassesConstants.ClassNine, "Physics", "Math", "NA");
            SaveRecord("Culley", "Sier", "8 Eggendart Drive", ClassesConstants.ClassNine, "Math", "Physics", "English");
            SaveRecord("Kelli", "Gillingham", "4473 Menomonie Terrace", ClassesConstants.ClassNine, "Physics", "Math", "English");
            SaveRecord("Paule", "Drysdell", "", ClassesConstants.ClassNine, "Math", "Physics", "NA");
            SaveRecord("Cherilyn", "Mc Menamin", "", ClassesConstants.ClassNine, "Physics", "Math", "English");
            SaveRecord("Moyna", "Kaasman", "81180 Pepper Wood Crossing", ClassesConstants.ClassTen, "Math", "Physics", "English");
            SaveRecord("Erie", "Slaymaker", "9 Summerview Junction", ClassesConstants.ClassTen, "Physics", "Math", "NA");
            SaveRecord("Alister", "Flintoft", "04 Dorton Point", ClassesConstants.ClassTen, "Math", "Physics", "English");
            SaveRecord("Olav", "Rintoul", "2422 Thompson Point", ClassesConstants.ClassTen, "Physics", "Math", "English");
            SaveRecord("Cleve", "Pavelin", "10 Prairieview Road", ClassesConstants.ClassTen, "Math", "Physics", "NA");
            SaveRecord("Edwina", "Gookey", "4073 Talmadge Point", ClassesConstants.ClassTen, "Physics", "Math", "English");
            SaveRecord("Ottilie", "Yashin", "", ClassesConstants.ClassTen, "Math", "Physics", "English");
            SaveRecord("Lucie", "Ablett", "7652 Riverside Point", ClassesConstants.ClassTen, "Physics", "Math", "NA");
            SaveRecord("Curran", "Clears", "0101 Ruskin Way", ClassesConstants.ClassTen, "Math", "Physics", "English");
            SaveRecord("Talia", "Shacklady", "", ClassesConstants.ClassTen, "Physics", "Math", "English");
            SaveRecord("Riane", "Rubra", "47313 7th Park", ClassesConstants.ClassTen, "Math", "Physics", "NA");
            SaveRecord("Issy", "Rangle", "69 Shelley Alley", ClassesConstants.ClassTen, "Physics", "Math", "English");
            SaveRecord("Friedrick", "Killigrew", "", ClassesConstants.ClassTen, "Math", "Physics", "English");
            SaveRecord("Collen", "Bulley", "6 Merrick Alley", ClassesConstants.ClassTen, "Physics", "Math", "NA");
            SaveRecord("Valentijn", "Haggerstone", "39 Browning Park", ClassesConstants.ClassTen, "Math", "Physics", "English");
            SaveRecord("Wylie", "Blampied", "", ClassesConstants.ClassTen, "Physics", "Math", "English");
            SaveRecord("Magdaia", "Gerdes", "7 Delladonna Circle", ClassesConstants.ClassTen, "Math", "Physics", "NA");
            SaveRecord("Lind", "Commander", "120 Dixon Junction", ClassesConstants.ClassTen, "Physics", "Math", "English");
            SaveRecord("Kalli", "Casino", "", ClassesConstants.ClassTen, "Math", "Physics", "English");
            SaveRecord("Jehu", "Wisniowski", "", ClassesConstants.ClassTen, "Physics", "Math", "NA");
            SaveRecord("Danielle", "Takkos", "", ClassesConstants.ClassTen, "Math", "Physics", "English");
            SaveRecord("Kate", "Cordes", "7 Monument Pass", ClassesConstants.ClassTen, "Physics", "Math", "English");
            SaveRecord("Cammy", "Wigglesworth", "", ClassesConstants.ClassTen, "Math", "Physics", "NA");
            SaveRecord("Chrisy", "Kinforth", "", ClassesConstants.ClassTen, "Physics", "Math", "English");
            SaveRecord("Dev", "Lestor", "09827 Oak Valley Lane", ClassesConstants.ClassTen, "Math", "Physics", "English");
            SaveRecord("Zebadiah", "Bach", "6 Anzinger Street", ClassesConstants.ClassTen, "Physics", "Math", "NA");
            SaveRecord("Caryn", "Brayshaw", "6 Beilfuss Park", ClassesConstants.ClassTen, "Math", "Physics", "English");
            SaveRecord("Mortimer", "Sannes", "631 Elka Trail", ClassesConstants.ClassTen, "Physics", "Math", "English");
            SaveRecord("Lev", "Pantone", "", ClassesConstants.ClassTen, "Math", "Physics", "NA");
            SaveRecord("Hailey", "Eady", "", ClassesConstants.ClassTen, "Physics", "Math", "English");
            SaveRecord("Althea", "Tompkins", "178 Scott Avenue", ClassesConstants.ClassTen, "Math", "Physics", "English");
            SaveRecord("Verine", "Benns", "3 Nelson Avenue", ClassesConstants.ClassTen, "Physics", "Math", "NA");
            SaveRecord("Lorilee", "Waghorne", "", ClassesConstants.ClassTen, "Math", "Physics", "English");
            SaveRecord("Pedro", "Froggatt", "7 Arrowood Court", ClassesConstants.ClassTen, "Physics", "Math", "English");
            SaveRecord("Katharine", "Cominotti", "32 Valley Edge Hill", ClassesConstants.ClassTen, "Math", "Physics", "NA");
            SaveRecord("Jennilee", "Brandi", "8809 Cherokee Parkway", ClassesConstants.ClassTen, "Physics", "Math", "English");
            SaveRecord("Carole", "Moberley", "886 Ronald Regan Point", ClassesConstants.ClassTen, "Math", "Physics", "English");
            SaveRecord("Elvin", "Stive", "509 Eastwood Place", ClassesConstants.ClassTen, "Physics", "Math", "NA");
            SaveRecord("Joletta", "Plumptre", "", ClassesConstants.ClassTen, "Math", "Physics", "English");
            SaveRecord("Evita", "Slay", "", ClassesConstants.ClassTen, "Physics", "Math", "English");
            SaveRecord("Jessee", "Thorne", "3667 Armistice Park", ClassesConstants.ClassTen, "Math", "Physics", "NA");
            SaveRecord("Ulberto", "de Zamora", "41247 Artisan Junction", ClassesConstants.ClassTen, "Physics", "Math", "English");
            SaveRecord("Ginni", "Ferrieres", "91 Johnson Parkway", ClassesConstants.ClassTen, "Math", "Physics", "English");
            SaveRecord("Eldin", "Jennings", "", ClassesConstants.ClassTen, "Physics", "Math", "NA");
            SaveRecord("Samara", "Kloster", "", ClassesConstants.ClassTen, "Math", "Physics", "English");
            SaveRecord("Wittie", "Chilcott", "", ClassesConstants.ClassTen, "Physics", "Math", "English");
            SaveRecord("Marv", "Gason", "", ClassesConstants.ClassTen, "Math", "Physics", "NA");
            SaveRecord("Cherise", "Self", "", ClassesConstants.ClassTen, "Physics", "Math", "English");
            SaveRecord("Hazel", "Tomblin", "", ClassesConstants.ClassTen, "Math", "Physics", "English");
            SaveRecord("Bjorn", "Balmadier", "459 Manufacturers Point", ClassesConstants.ClassTen, "Physics", "Math", "NA");
            SaveRecord("Dwight", "Godding", "", ClassesConstants.ClassTen, "Math", "Physics", "English");
            SaveRecord("Pablo", "Gluyas", "2 Bellgrove Crossing", ClassesConstants.ClassTen, "Physics", "Math", "English");
            SaveRecord("Devin", "Thaine", "547 Clove Park", ClassesConstants.ClassTen, "Math", "Physics", "NA");
            SaveRecord("Rianon", "Conradie", "", ClassesConstants.ClassTen, "Physics", "Math", "English");
            SaveRecord("Morgan", "Camamill", "5 Bay Plaza", ClassesConstants.ClassTen, "Math", "Physics", "English");
            SaveRecord("Ody", "Cordeau]", "", ClassesConstants.ClassTen, "Physics", "Math", "NA");
            SaveRecord("Bordy", "Curlis", "", ClassesConstants.ClassTen, "Math", "Physics", "English");
            SaveRecord("Larisa", "Segrave", "24 Amoth Junction", ClassesConstants.ClassTen, "Physics", "Math", "English");
            SaveRecord("Sonnie", "MacAllan", "7 Maywood Place", ClassesConstants.ClassTen, "Math", "Physics", "NA");
            SaveRecord("Ninnetta", "Minton", "6 Shasta Center", ClassesConstants.ClassTen, "Physics", "Math", "English");
            SaveRecord("Anastasia", "Jury", "4 Steensland Place", ClassesConstants.ClassTen, "Math", "Physics", "English");
            SaveRecord("Rhodia", "Towne", "57711 Jenifer Parkway", ClassesConstants.ClassTen, "Physics", "Math", "NA");
            SaveRecord("Doretta", "Seeman", "2772 Redwing Center", ClassesConstants.ClassTen, "Math", "Physics", "English");
            SaveRecord("D'arcy", "O'Day", "", ClassesConstants.ClassTen, "Physics", "Math", "English");
            SaveRecord("Regan", "Ashbey", "", ClassesConstants.ClassTen, "Math", "Physics", "NA");
            SaveRecord("Celene", "Diloway", "89077 Basil Junction", ClassesConstants.ClassTen, "Physics", "Math", "English");
            SaveRecord("Geri", "Pallasch", "9680 Daystar Crossing", ClassesConstants.ClassTen, "Math", "Physics", "English");
            SaveRecord("Tori", "Kingston", "663 Oakridge Park", ClassesConstants.ClassTen, "Physics", "Math", "NA");
            SaveRecord("Kellie", "Bilsborrow", "8 Cherokee Court", ClassesConstants.ClassTen, "Math", "Physics", "English");
            SaveRecord("Padriac", "Gonsalvez", "9016 Eastlawn Court", ClassesConstants.ClassTen, "Physics", "Math", "English");
            SaveRecord("Lora", "Rome", "", ClassesConstants.ClassTen, "Math", "Physics", "NA");
            SaveRecord("Eveline", "Stoneman", "977 Aberg Way", ClassesConstants.ClassTen, "Physics", "Math", "English");
            SaveRecord("Conney", "Caccavale", "90 Arizona Pass", ClassesConstants.ClassTen, "Math", "Physics", "English");
            SaveRecord("Howey", "Nolder", "8681 Graceland Avenue", ClassesConstants.ClassTen, "Physics", "Math", "NA");
            SaveRecord("Georgeta", "Nuemann", "", ClassesConstants.ClassTen, "Math", "Physics", "English");
            SaveRecord("Giovanni", "Lante", "10754 Bultman Way", ClassesConstants.ClassTen, "Physics", "Math", "English");
            SaveRecord("Sherwood", "Pavolini", "", ClassesConstants.ClassTen, "Math", "Physics", "NA");
            SaveRecord("Sadye", "Wallicker", "4925 Del Sol Street", ClassesConstants.ClassTen, "Physics", "Math", "English");
            SaveRecord("Marvin", "Spraggs", "09 Spaight Road", ClassesConstants.ClassTen, "Math", "Physics", "English");
            SaveRecord("Jess", "Yoseloff", "4263 School Point", ClassesConstants.ClassTen, "Physics", "Math", "NA");
            SaveRecord("Gifford", "Buzek", "18 Harbort Way", ClassesConstants.ClassTen, "Math", "Physics", "English");
            SaveRecord("Innis", "Langshaw", "04830 Carpenter Park", ClassesConstants.ClassTen, "Physics", "Math", "English");
            SaveRecord("Thoma", "Coats", "25971 Hoffman Alley", ClassesConstants.ClassTen, "Math", "Physics", "NA");
            SaveRecord("Almira", "Rudgerd", "", ClassesConstants.ClassTen, "Physics", "Math", "English");
            SaveRecord("Peri", "Wetherhead", "23579 Glendale Alley", null, "Math", "Physics", "English");
            SaveRecord("Milton", "Bonett", "", null, "Physics", "Math", "NA");
            SaveRecord("Netti", "Cookley", "35579 Paget Alley", null, "Math", "Physics", "English");
            SaveRecord("Stanislaw", "Nerval", "", null, "Physics", "Math", "English");
            SaveRecord("Adriana", "Pedrick", "86277 Merchant Hill", null, "Math", "Physics", "NA");
            SaveRecord("Fanya", "Loughlin", "1 Farmco Crossing", null, "Physics", "Math", "English");
            SaveRecord("Doro", "Altham", "", null, "Math", "Physics", "English");
            SaveRecord("Broddie", "Cosgreave", "2 Memorial Alley", null, "Physics", "Math", "NA");
            SaveRecord("Fred", "Lewinton", "761 Morningstar Road", null, "Math", "Physics", "English");
            SaveRecord("Willem", "Dumbarton", "7 Basil Pass", null, "Physics", "Math", "English");
            SaveRecord("Wain", "Gorini", "02 Almo Terrace", null, "Math", "Physics", "NA");
            SaveRecord("Ellary", "Slayford", "", null, "Physics", "Math", "English");
            SaveRecord("Merissa", "Hollyar", "387 Bartillon Lane", null, "Math", "Physics", "English");
            SaveRecord("Cull", "Roloff", "54 Manufacturers Point", null, "Physics", "Math", "NA");
            SaveRecord("Abby", "Monck", "53 Portage Alley", null, "Math", "Physics", "English");
            SaveRecord("Clare", "Nann", "", null, "Physics", "Math", "English");
            SaveRecord("Dom", "Heaphy", "7007 Dovetail Plaza", null, "Math", "Physics", "NA");
            SaveRecord("Bea", "Windress", "", null, "Physics", "Math", "English");
            SaveRecord("Kanya", "Longhirst", "0602 Gerald Hill", null, "Math", "Physics", "English");
            SaveRecord("Benedetto", "Eaton", "", null, "Physics", "Math", "NA");
            SaveRecord("Alexandra", "Pischoff", "8503 Barby Pass", null, "Math", "Physics", "English");
            SaveRecord("Nataline", "Cromwell", "", null, "Physics", "Math", "English");
            SaveRecord("Donni", "Swannack", "", null, "Math", "Physics", "NA");
            SaveRecord("Skipp", "Elion", "67657 Lindbergh Drive", null, "Physics", "Math", "English");
            SaveRecord("Charmian", "Constant", "524 School Lane", null, "Math", "Physics", "English");
            SaveRecord("Stephine", "Wegener", "55 Prairieview Road", null, "Physics", "Math", "NA");
            SaveRecord("Darryl", "Hebborne", "1811 Union Crossing", null, "Math", "Physics", "English");
            SaveRecord("Genevra", "Wrinch", "", null, "Physics", "Math", "English");
            SaveRecord("Gayler", "Maron", "45772 Kipling Center", null, "Math", "Physics", "NA");
            SaveRecord("Jereme", "Squirrel", "8322 Mallory Alley", null, "Physics", "Math", "English");
            SaveRecord("Giordano", "Gerger", "3610 Union Hill", null, "Math", "Physics", "English");
            SaveRecord("Faye", "Sworn", "924 Rigney Road", null, "Physics", "Math", "NA");
            SaveRecord("Veradis", "Sullly", "3 Mariners Cove Lane", null, "Math", "Physics", "English");
            SaveRecord("Darnell", "Prawle", "5 Farwell Place", null, "Physics", "Math", "English");
            SaveRecord("Tiebout", "Pritchitt", "", null, "Math", "Physics", "NA");
            SaveRecord("Robin", "Munkton", "", null, "Physics", "Math", "English");
            SaveRecord("Jehanna", "Aggott", "", null, "Math", "Physics", "English");
            SaveRecord("Obidiah", "Whal", "937 Transport Center", null, "Physics", "Math", "NA");
            SaveRecord("Lonna", "Haggar", "", null, "Math", "Physics", "English");
            SaveRecord("Maude", "Hawler", "8538 Rieder Avenue", null, "Physics", "Math", "English");
            SaveRecord("Scot", "Seabridge", "", null, "Math", "Physics", "NA");
            SaveRecord("Juditha", "Bryce", "2 Blue Bill Park Junction", null, "Physics", "Math", "English");
            SaveRecord("Jeannette", "Vertey", "1 Merrick Place", null, "Math", "Physics", "English");
            SaveRecord("Janene", "Chimienti", "", null, "Physics", "Math", "NA");
            SaveRecord("Binky", "McEntegart", "7777 Lillian Parkway", null, "Math", "Physics", "English");
            SaveRecord("Wilow", "Hadcock", "", null, "Physics", "Math", "English");
            SaveRecord("Felecia", "Brandi", "909 Nova Plaza", null, "Math", "Physics", "NA");
            SaveRecord("Romola", "Guillet", "752 Village Green Parkway", null, "Physics", "Math", "English");
            SaveRecord("Malena", "Musselwhite", "2854 Vahlen Road", null, "Math", "Physics", "English");
            SaveRecord("Penelope", "Dinning", "1748 Rowland Place", null, "Physics", "Math", "NA");
            SaveRecord("Marlie", "Bonnet", "", null, "Math", "Physics", "English");
            SaveRecord("Alvie", "Bray", "", null, "Physics", "Math", "English");
            SaveRecord("Blondell", "Shalliker", "24944 Killdeer Trail", null, "Math", "Physics", "NA");
            SaveRecord("Cassandra", "Dugan", "5538 Roxbury Pass", null, "Physics", "Math", "English");
            SaveRecord("Netti", "McNess", "", null, "Math", "Physics", "English");
            SaveRecord("Boothe", "Joslyn", "", null, "Physics", "Math", "NA");
            SaveRecord("Christiane", "Gantlett", "261 Service Trail", null, "Math", "Physics", "English");
            SaveRecord("Jsandye", "Ropkes", "", null, "Physics", "Math", "English");
            SaveRecord("Janina", "Duran", "595 Kropf Trail", null, "Math", "Physics", "NA");
            SaveRecord("Antoine", "Moxsom", "", null, "Physics", "Math", "English");
            SaveRecord("Bart", "Ames", "", null, "Math", "Physics", "English");
            SaveRecord("Maximilianus", "Cahalan", "", null, "Physics", "Math", "NA");
            SaveRecord("Dwight", "Neillans", "9731 Dorton Place", null, "Math", "Physics", "English");
            SaveRecord("Aldo", "Idill", "", null, "Physics", "Math", "English");
            SaveRecord("Matty", "Speight", "", null, "Math", "Physics", "NA");
            SaveRecord("Greg", "Fraschini", "", null, "Physics", "Math", "English");
            SaveRecord("Audy", "Feldberg", "1 Hauk Center", null, "Math", "Physics", "English");
            SaveRecord("Ealasaid", "Martignon", "9141 Bashford Junction", null, "Physics", "Math", "NA");
            SaveRecord("Griff", "Baum", "6 Delladonna Crossing", null, "Math", "Physics", "English");
            SaveRecord("Janos", "Benzing", "84 Orin Place", null, "Physics", "Math", "English");
            SaveRecord("Marijo", "Fairbrace", "", null, "Math", "Physics", "NA");
            SaveRecord("Forster", "Camel", "", null, "Physics", "Math", "English");
            SaveRecord("Kerby", "Davenhall", "11 Mariners Cove Court", null, "Math", "Physics", "English");
            SaveRecord("Stormi", "Vakhonin", "252 Northfield Parkway", null, "Physics", "Math", "NA");
            SaveRecord("Nerty", "Von Der Empten", "2122 Buena Vista Road", null, "Math", "Physics", "English");
            SaveRecord("Evangeline", "Halbord", "5700 Welch Crossing", null, "Physics", "Math", "English");
            SaveRecord("Chariot", "Candish", "", null, "Math", "Physics", "NA");
            SaveRecord("Laney", "Gullivent", "44 Mendota Hill", null, "Physics", "Math", "English");
            SaveRecord("Loleta", "Bruckental", "49183 Artisan Parkway", null, "Math", "Physics", "English");
            SaveRecord("Janis", "Ference", "1 Schiller Road", null, "Physics", "Math", "NA");


        }

        private void SaveRecord(string firstName, string lastname, string address = null, int? classOf = null, string subject01 = null, string subject02 = null, string subject03 = null)
        {
            var isGraduted = classOf == null ? "Yes" : "No";
            var student = new Student
            {
                id = Guid.NewGuid(),
                first_name = firstName,
                last_name = lastname,
                class_of = classOf,
                is_graduated = isGraduted,
                address = address,
                subject_01 = subject01,
                subject_02 = subject02,
                subject_03 = subject03

            };
            Insert.IntoTable(TableName).Row(student);
        }
    }
}